apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-frontend
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
    {{- toYaml .Values.labels.frontend | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP
      name: frontend
  selector:
    {{- include "my-chart.selectorLabels" . | nindent 4 }}
